[project]
name = "easy-adb-controller"
version = "0.1.0"
description = "adb module to control android in easy way"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "pure-python-adb>=0.3.0.dev0",
    "requests>=2.32.3",
]

